#!/usr/bin/env bash
# Generates the key tables for hyprlang's keyed special categories (device{}, monitorv2{}).
#
# Those keys were registered by hand in the legacy config manager rather than declared in
# ConfigValues.cpp, so the lists are read back out of that registration code.
#
# usage: gen_special_values.sh <legacy ConfigManager.cpp> <out.hpp>

set -euo pipefail

src="${1:?legacy ConfigManager.cpp path}"
out="${2:?output header path}"

emit_category() {
    local category="$1" name="$2"

    echo "    inline constexpr std::pair<std::string_view, eSpecialValueType> $name[] = {"

    grep -o "addSpecialConfigValue(\"$category\", \"[^\"]*\", [^)]*)" "$src" | while read -r line; do
        key=$(printf '%s' "$line" | sed -n "s/.*\"$category\", \"\([^\"]*\)\".*/\1/p")
        rest=$(printf '%s' "$line" | sed -n "s/.*\"$category\", \"[^\"]*\", \(.*\))\$/\1/p")

        case "$rest" in
            *Hyprlang::INT*) type=SPECIAL_VALUE_INT ;;
            *Hyprlang::FLOAT* | *F\}*) type=SPECIAL_VALUE_FLOAT ;;
            *) type=SPECIAL_VALUE_STRING ;;
        esac

        echo "        {\"$key\", $type},"
    done

    echo "    };"
    echo
}

{
    echo "// Generated by tools/gen_special_values.sh. Do not edit."
    echo "#pragma once"
    echo
    echo "#include <cstdint>"
    echo "#include <string_view>"
    echo "#include <utility>"
    echo
    echo "namespace H2L {"
    echo "    enum eSpecialValueType : uint8_t {"
    echo "        SPECIAL_VALUE_INT = 0,"
    echo "        SPECIAL_VALUE_FLOAT,"
    echo "        SPECIAL_VALUE_STRING,"
    echo "    };"
    echo

    emit_category device DEVICE_VALUES
    emit_category monitorv2 MONITORV2_VALUES

    echo "}"
} > "$out"
