#!/usr/bin/env bash
# Generates the window/layer rule vocabulary from Hyprland's rule engine.
#
# Both config languages name rule effects and match properties with the same strings, so
# the lists are read out of the tables that define them rather than restated here:
#   EFFECT_STRINGS      in {Window,Layer}RuleEffectContainer.cpp
#   MATCH_PROP_STRINGS  in Rule.cpp
#
# usage: gen_rule_names.sh <hyprland src dir> <out.hpp>

set -euo pipefail

src="${1:?hyprland src dir}"
out="${2:?output header path}"

emit_effects() {
    local file="$1" name="$2"
    echo "    inline constexpr std::string_view $name[] = {"
    awk '/EFFECT_STRINGS = \{/,/^\};/' "$file" |
        grep -o '"[^"]*"' |
        grep -v '__internal' |
        sed 's/^/        /; s/$/,/'
    echo "    };"
    echo
}

{
    echo "// Generated by tools/gen_rule_names.sh. Do not edit."
    echo "#pragma once"
    echo
    echo "#include <string_view>"
    echo
    echo "namespace H2L {"

    emit_effects "$src/desktop/rule/windowRule/WindowRuleEffectContainer.cpp" WINDOW_RULE_EFFECTS
    emit_effects "$src/desktop/rule/layerRule/LayerRuleEffectContainer.cpp" LAYER_RULE_EFFECTS

    echo "    inline constexpr std::string_view RULE_MATCH_PROPS[] = {"
    awk '/MATCH_PROP_STRINGS/,/\}\)\);/' "$src/desktop/rule/Rule.cpp" |
        grep -o '{RULE_PROP_[A-Z_]*, "[^"]*"}' |
        sed 's/.*, "\([^"]*\)".*/        "\1",/'
    echo "    };"
    echo "}"
} > "$out"
