#!/usr/bin/env bash
# Generates the per-device option table from the legacy config manager.
#
# `device { ... }` blocks are a hyprlang special category whose keys were registered by
# hand in the legacy manager rather than declared in ConfigValues.cpp, so the list is read
# back out of that registration code instead of being retyped here.
#
# usage: gen_device_values.sh <legacy ConfigManager.cpp> <out.hpp>

set -euo pipefail

src="${1:?legacy ConfigManager.cpp path}"
out="${2:?output header path}"

{
    echo "// Generated by tools/gen_device_values.sh. Do not edit."
    echo "// Source: src/config/legacy/ConfigManager.cpp @ $(basename "$(dirname "$src")")"
    echo "#pragma once"
    echo
    echo "#include <string_view>"
    echo "#include <utility>"
    echo
    echo "namespace H2L {"
    echo "    enum eDeviceValueType : uint8_t {"
    echo "        DEVICE_VALUE_INT = 0,"
    echo "        DEVICE_VALUE_FLOAT,"
    echo "        DEVICE_VALUE_STRING,"
    echo "    };"
    echo
    echo "    inline constexpr std::pair<std::string_view, eDeviceValueType> DEVICE_VALUES[] = {"

    grep -o 'addSpecialConfigValue("device", "[^"]*", [^)]*)' "$src" | while read -r line; do
        name=$(printf '%s' "$line" | sed -n 's/.*"device", "\([^"]*\)".*/\1/p')
        rest=$(printf '%s' "$line" | sed -n 's/.*"device", "[^"]*", \(.*\))$/\1/p')

        case "$rest" in
            *Hyprlang::INT*) type=DEVICE_VALUE_INT ;;
            *Hyprlang::FLOAT* | *F\}*) type=DEVICE_VALUE_FLOAT ;;
            *STRVAL_EMPTY* | *\"*) type=DEVICE_VALUE_STRING ;;
            *) type=DEVICE_VALUE_STRING ;;
        esac

        echo "        {\"$name\", $type},"
    done

    echo "    };"
    echo "}"
} > "$out"
